create table if not exists public.leituras (
  id bigint generated by default as identity primary key,
  data_iso timestamptz not null default now(),
  horario text,
  nivel text,
  bomba text,
  corrente numeric,
  tensao_bateria numeric,
  carga_bateria numeric,
  tensao_solar numeric,
  alerta text,
  conexao text,
  simulado boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists leituras_data_iso_idx
  on public.leituras (data_iso desc);

alter table public.leituras enable row level security;

drop policy if exists "Bloquear leitura publica de leituras" on public.leituras;
create policy "Bloquear leitura publica de leituras"
  on public.leituras
  for select
  using (false);

drop policy if exists "Bloquear escrita publica de leituras" on public.leituras;
create policy "Bloquear escrita publica de leituras"
  on public.leituras
  for insert
  with check (false);
