services:
  - type: web
    name: sistema-mecatronico-sustentavel
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MODO_CLOUD
        value: "true"
      - key: TRUST_PROXY
        value: "true"
      - key: BAUD_RATE
        value: "9600"
      - key: SUPABASE_TABELA
        value: "leituras"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
