services:
  - type: web
    name: sistema-mecatronico-sustentavel
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MODO_CLOUD
        value: "true"
      - key: TRUST_PROXY
        value: "true"
      - key: BAUD_RATE
        value: "9600"
